### ISSUE TITLE
2.x todo

### ISSUE THREAD

**Issue by cweagans** [cweagans/composer-patches#93]
This should probably be a bunch of separate tickets in a milestone, but I don't feel like it. This is easier: 

## 2.0.0 release blockers

- [x] Build passing
- [ ] 100% code coverage for all business logic (excl: composer boilerplate)
- [ ] Identify 5 acceptance test scenarios for core functionality + build those tests
- [ ] Docs
    - [ ] Troubleshooting guide (#198)
    - [ ] Configuration & usage
    - [ ] Requirements (OS support, software dependencies, etc)
    - [ ] Extension points (events, capabilities)
    - [ ] _docs only_: how to apply patches to the root package/non composer packages (https://github.com/cweagans/composer-patches/issues/76)
- [ ] CLI command for adding patches (https://github.com/cweagans/composer-patches/issues/81)
- [ ] Define patch depth per-patch (extended format only)
- [ ] Implement -p guessing for when patch depth isn't specified (but fail if multiple depths can be successfully applied)
- [ ] Prevent interactive mode (#196)
- [ ] checkPatches() is too heavy handed (https://github.com/cweagans/composer-patches/issues/135)
- [ ] Dispatch events where needed
- [ ] composer-preserve-paths must work (https://github.com/cweagans/composer-patches/issues/42)
- [ ] Allow ignoring specific patches (port to 2.x)
- [ ] Allow ignoring all patches on a package (port to 2.x)
- [ ] Make sure composer lock behavior is respected (https://github.com/cweagans/composer-patches/issues/12)
- [x] Remove dependency patch resolution

## Wishlist
- [x] Split out patch resolution into composer capabilities (https://github.com/cweagans/composer-patches/pull/212)
- [x] Remove patch report generation (https://github.com/cweagans/composer-patches/issues/140)
- [ ] Dedupe patches based on sha1
- [ ] Unbreak FreeBSD (#184, #159, #74) ?
- [ ] Address patcher issues (https://github.com/cweagans/composer-patches/issues/172)
- [ ] Composer install fails with contrib project and bad patch (https://github.com/cweagans/composer-patches/issues/127)
- [ ] Allow disabling removal of patched packages (https://github.com/cweagans/composer-patches/issues/126)
- [ ] checkPatches should diff what's in composer.lock and composer.json, and if there's a mismatch, remove the package and reinstall it if appropriate (https://github.com/cweagans/composer-patches/issues/98
- [ ] Cache downloaded patches (https://github.com/cweagans/composer-patches/issues/35)
- [ ] Allow force-enabling patching to just have dependency patches (https://github.com/cweagans/composer-patches/issues/16)
- [ ] Research: pure PHP implementation of Patch?
- [ ] Local patches defined by dependencies should be relative to the root of the dependency (https://github.com/cweagans/composer-patches/issues/39
- [ ] Apply patch to arbitrary path (https://github.com/cweagans/composer-patches/issues/76)

## Evaluate other packages and merge functionality
- [ ] https://packagist.org/packages/nathandentzau/composer-patches-dev
- [ ] https://packagist.org/packages/szeidler/composer-patches-cli
- [ ] vaimo/composer-patches

**Comment by cweagans** [comment]
Feel free to submit PRs for any of these things if they aren't checked off.

**Comment by marclaporte** [comment]
About "Research: Pure PHP implementation of patch?" -> The patch utility is not always available and thus, we'd like this to be handled by cweagans/composer-patches (directly or indirectly)

Would this work?
https://gist.github.com/fmazerolle/1712670
https://gist.github.com/fmazerolle/1707075

Are you aware of any other suitable libs? Anything already on Packagist.org?

Thanks!

**Comment by axel-rutz** [comment]
> Maybe copy in the patch defs too? [to lock file]

The whole patch? I'd say this can become too huge and a hash is enough.

**Comment by ElijahLynn** [comment]
This issue summary was updated last night here at DrupalCon and is up to date with new priorities for the 2.x release.

**Comment by cweagans** [comment]
I added some notes to https://github.com/cweagans/composer-patches/wiki/2.0.0-Architecture-Notes

**Comment by cweagans** [comment]
This is pretty outdated now.
